mixed-port: 7890
#---------------------------------------------------#
## 更新：2020-07-11 10:36:22
## 感谢：https://github.com/Hackl0us/SS-Rule-Snippet
#---------------------------------------------------#


# Linux 和 macOS 的 redir 代理端口
redir-port: 7892

# 允许局域网的连接
allow-lan: false

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: error
# Clash 的 RESTful API
external-controller: '127.0.0.1:9090'

# RESTful API 的口令
secret: ''

dns:
  enable: true
  ipv6: false
  listen: '0.0.0.0:53'
  use-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    # - 1.1.1.1
    - 8.8.8.8
    # - 202.120.224.6
    # - 114.114.114.114
    # - 'tls://8.8.8.8'
    # - 'https://doh.pub/dns-query'
    # - 'https://dns.alidns.com/dns-query'
  fallback:
    - 'https://doh.pub/dns-query'
    - 'https://dns.cloudflare.com/dns-query'
    - 'https://dns.twnic.tw/dns-query'
    - 'tls://8.8.4.4:853'
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

proxy-providers:
  FF:
    type: http
    path: ./profiles/FF.yaml
    url: "https://www.yhc1314dy.link/api/v1/client/subscribe?token=e346876557e7e276980ad35c76d07f50"
    interval: 300
    health-check:
      enable: true
      url: "http://www.gstatic.com/generate_204"
      interval: 300

  FF新加坡:
    type: file
    path: ./profiles/FF.yaml
    interval: 300
    health-check:
      enable: true
      url: "http://www.gstatic.com/generate_204"
      interval: 300
    filter: 新加坡

  FF日本:
    type: file
    path: ./profiles/FF.yaml
    interval: 300
    health-check:
      enable: true
      url: "http://www.gstatic.com/generate_204"
      interval: 300
    filter: 日本

proxy-groups:
  - name: OPENAI
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use:
      - FF新加坡
      - FF日本

  - name: 故障转移
    type: fallback
    url: 'http://www.gstatic.com/generate_204'
    interval: 600
    use:
      - FF新加坡
      - FF日本

  - name: 查看节点
    type: select
    use:
      - FF新加坡
      - FF日本

  - name: 手动选择
    type: select
    use:
      - FF

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  tiktok:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.yaml"
    path: ./ruleset/tiktok.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  # - RULE-SET,reject,REJECT # 暂不屏蔽广告,避免有些网站无法访问
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,OPENAI
  - RULE-SET,telegramcidr,OPENAI
  - RULE-SET,tiktok,OPENAI # 走OPENAI节点
  - RULE-SET,proxy,OPENAI # 走OPENAI节点
  - RULE-SET,gfw,OPENAI # 走OPENAI节点
  - RULE-SET,greatfire,OPENAI # 走OPENAI节点
  - RULE-SET,tld-not-cn,OPENAI # 走OPENAI节点
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  # 这些是自定义规则
  - # develop
  - DOMAIN-SUFFIX,eastmoney.com,DIRECT
  - # gov
  - DOMAIN-SUFFIX,gov.cn,DIRECT
  - DOMAIN-SUFFIX,cn,DIRECT
  - # coffee
  - DOMAIN-SUFFIX,captive.apple.com,DIRECT
  - DOMAIN-SUFFIX,_dns.resolver.arpa,DIRECT
  - DOMAIN-SUFFIX,wiwide.com,DIRECT
  - DOMAIN-SUFFIX,arubanetworks.com,DIRECT
  - # figma
  - DOMAIN-SUFFIX,figma.com,DIRECT
  - # openai
  - DOMAIN-SUFFIX,openai.com,OPENAI
  - DOMAIN-SUFFIX,api.openai.com,OPENAI
  - DOMAIN-SUFFIX,auth0.openai.com,OPENAI
  - DOMAIN-SUFFIX,chat.openai.com,OPENAI
  - DOMAIN-SUFFIX,cdn.openai.com,OPENAI
  - DOMAIN-SUFFIX,openaiassets.com,OPENAI
  - DOMAIN-SUFFIX,openai-public.azureedge.net,OPENAI
  - DOMAIN-SUFFIX,openai-public.azure.com,OPENAI
  - DOMAIN-SUFFIX,pay.openai.com,OPENAI
  - DOMAIN-SUFFIX,challenges.cloudflare.com,OPENAI
  - DOMAIN-SUFFIX,platform.openai.com,OPENAI
  - # azure
  - DOMAIN-SUFFIX,azure.com,OPENAI
  - # claude.ai
  - DOMAIN-SUFFIX,claude.ai,OPENAI
  - # perplexity.ai
  - DOMAIN-SUFFIX,perplexity.ai,OPENAI
  - # grok.com
  - DOMAIN-SUFFIX,grok.com,OPENAI
  - # bing.com
  - DOMAIN-SUFFIX,bing.com,OPENAI
  - # stripe.com
  - DOMAIN-SUFFIX,invoice.stripe.com,OPENAI
  - DOMAIN-SUFFIX,stripe.com,OPENAI
  - # youtube
  - DOMAIN-SUFFIX,youtube.com,OPENAI
  - DOMAIN,youtubei.googleapis.com,OPENAI
  - DOMAIN,yt3.ggpht.com,OPENAI
  - DOMAIN-KEYWORD,youtube,OPENAI
  - # 所有未匹配上的域名走OPENAI
  - MATCH,OPENAI

  - # 其他可能影响openai
  # - DOMAIN,openaiapi-site.azureedge.net, OPENAI
  # - DOMAIN,chat.openai.com.cdn.cloudflare.net, OPENAI
  # - DOMAIN-SUFFIX,auth0.com,OPENAI
  # - DOMAIN-SUFFIX,ai.com,OPENAI
  # - DOMAIN-SUFFIX,cloudflare.com,OPENAI
  # - DOMAIN-SUFFIX,deepl.com,OPENAI
  # - DOMAIN-SUFFIX,live.com,OPENAI
  # - DOMAIN-SUFFIX,sentry.io,OPENAI
  # - DOMAIN-SUFFIX,vimeocdn.com,OPENAI
  # - DOMAIN-SUFFIX,hcaptcha.com,OPENAI
  # - DOMAIN-SUFFIX,gvt1.com,OPENAI
  # - DOMAIN-SUFFIX,gvt2.com,OPENAI
  # - DOMAIN-SUFFIX,gvt3.com,OPENAI
  # - DOMAIN-SUFFIX,recaptcha.net,OPENAI
  # - DOMAIN-SUFFIX,akamaized.net,OPENAI
  # - DOMAIN-SUFFIX,googleapis.com,OPENAI
  # - DOMAIN-SUFFIX,gstatic.com,OPENAI
  # - DOMAIN-SUFFIX,vimeo.com,OPENAI
  # - DOMAIN-SUFFIX,googletagmanager.com,OPENAI
  # - DOMAIN-SUFFIX,f7tk.com,OPENAI
  # - DOMAIN-SUFFIX,doubleclick.net,OPENAI
  # - DOMAIN-SUFFIX,google-analytics.com,OPENAI
  # - DOMAIN-SUFFIX,intercom.io,OPENAI
  # - DOMAIN-SUFFIX,statsigapi.net,OPENAI
  # - DOMAIN-SUFFIX,featuregates.org,OPENAI
  # - DOMAIN-SUFFIX,intercomcdn.com,OPENAI
  # - DOMAIN-SUFFIX,pki.goog,OPENAI
  # - DOMAIN-SUFFIX,identrust.com,OPENAI
  # - DOMAIN-SUFFIX,cloudflareinsights.com,OPENAI
  # - DOMAIN-SUFFIX,edgecompute.app,OPENAI
  # - DOMAIN-SUFFIX,compute-pipe.com,OPENAI

